//create a synth and connect it to the main output (your speakers)
const synth = new Tone.Synth().toDestination();

const now = Tone.now()
synth.triggerAttackRelease("E4", "8n", now)
synth.triggerAttackRelease("E4", "8n", now + 0.5)
synth.triggerAttackRelease("F4", "8n", now + 1)
synth.triggerAttackRelease("G4", "8n", now + 1.5)
synth.triggerAttackRelease("G4", "8n", now + 2.0)
synth.triggerAttackRelease("F4", "8n", now + 2.5)
synth.triggerAttackRelease("E4", "8n", now + 3.0)
synth.triggerAttackRelease("D4", "8n", now + 3.5)
synth.triggerAttackRelease("C4", "8n", now + 4.0)
synth.triggerAttackRelease("C4", "8n", now + 4.5)
synth.triggerAttackRelease("D4", "8n", now + 5.0)
synth.triggerAttackRelease("E4", "8n", now + 5.5)
synth.triggerAttackRelease("E4", "8n", now + 6.0)
synth.triggerAttackRelease("D4", "8n", now + 6.5)
synth.triggerAttackRelease("D4", "8n", now + 7.0)
